### ISSUE TITLE
Replace gruntfile by 2 npm scripts

### ISSUE THREAD

**Issue by MoOx** [harthur/color#51]

**Comment by ZuBB** [comment]
Hi @MoOx 

You dropped grunt with browserify task. But did not added it as npm script. Do you have a plan to add it?

**Comment by MoOx** [comment]
Hi, I don't see the point to use a standalone script in a commonjs environnement (node/npm/browserify).
What is your use case ?

**Comment by ZuBB** [comment]
I used to create a single file with all libs included. that file is sent to customer

**Comment by MoOx** [comment]
I understand that you are just concatenating "simple" javascripts files ?
If so, you can create a standalone color.js file by doing:

```console
$ npm install color browserify
$ ./node_modules/.bin/browserify --standalone Color ./node_modules/color/index.js -o color.js
```

This should create you a standalone color.js that expose globally a window.Color var like before.

**Comment by ZuBB** [comment]
Color lib is used in framework which is used in 3+ products(scripts)

I do not like idea doing that manually or managing that patch in custom branch and having constant merge/rebase

**Comment by MoOx** [comment]
You do not have to make this as a patch, you can integrate this command in a setup script or as a postinstall hook.
How do you consume color.js ? With npm ?

**Comment by ZuBB** [comment]
due to my custom env I forced to used statically build version "color.js" which is added in framework repo. that file is included into final file with help of grunt(-contirb-copy). but I still want to find a way how to deal with 'require' method in my env and use version of color lib cooked with grunt or npm. 

With help of command you provided earlier (and several lines of js code) I will do that

Thanks
